# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/katherine/Linux_Unreal_Engine_5.2.1
GAMEPROJECTFILE =/home/katherine/Documents/Unreal Projects/FlockingGame/FlockingGame.uproject

TARGETS = \
	FlockingGame-Linux-DebugGame  \
	FlockingGame-Linux-Shipping  \
	FlockingGame \
	FlockingGameEditor-Linux-DebugGame  \
	FlockingGameEditor-Linux-Shipping  \
	FlockingGameEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend FlockingGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug FlockingGameEditor-Linux-Debug


FlockingGame-Linux-DebugGame:
	 $(PROJECTBUILD) FlockingGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

FlockingGame-Linux-Shipping:
	 $(PROJECTBUILD) FlockingGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

FlockingGame:
	 $(PROJECTBUILD) FlockingGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

FlockingGameEditor-Linux-DebugGame:
	 $(PROJECTBUILD) FlockingGameEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

FlockingGameEditor-Linux-Shipping:
	 $(PROJECTBUILD) FlockingGameEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

FlockingGameEditor:
	 $(PROJECTBUILD) FlockingGameEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
